language: node_js
node_js: node
branches:
  only:
    - raw
before_script:
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install -g gulp
install:
  - npm install
script:
  - hexo clean
  - hexo g
  - gulp
after_success:
  #- hexo deploy
  - cd ./public
  - git init
  - git config --global user.name "baiyangliu" 
  - git config --global user.email "cun.liu@qq.com"
  - git add .
  - git commit -m "Updated by travis-ci at $(date)"
  - git push --force https://$DEPLOY_TOKEN@github.com/baiyangliu/baiyangliu.github.io.git master:master
