language: node_js
node_js: node
branches:
  only:
    - raw
before_script:
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install -g gulp
install:
  - npm install
script:
  - hexo clean
  - hexo g
  - hexo algolia
  - gulp
after_success:
  - echo $RSYNC_SECRET > rsync.secret
  - chmod 600 rsync.secret
  - rsync -vzrtopg --delete --progress --password-file=./rsync.secret ./public/* baiyangliu@baiyangliu.com::blog
  - rm -rf rsync.secret
  
  - cd ./public
  - echo "$BAIDU_VERIFY_CONTENT" > "$BAIDU_VERIFY_NAME"
  - echo "$GOOGLE_VERIFY_CONTENT" > "$GOOGLE_VERIFY_NAME"
  - echo "$WEBSCAN_360_VERIFY_CONTENT" > "$WEBSCAN_360_VERIFY_NAME"
  
  - echo 'callback0({qq:407453324,wechat:"baiyangliu",email:"lc@baiyangliu.com"});' > me0.js
  - echo 'callback1({qq:407453324,wechat:"baiyangliu",email:"lc@baiyangliu.com"});' > me1.js
  - echo 'callback2({qq:407453324,wechat:"baiyangliu",email:"lc@baiyangliu.com"});' > me2.js
  - echo 'callback3({qq:407453324,wechat:"baiyangliu",email:"lc@baiyangliu.com"});' > me3.js
  - echo 'callback4({qq:407453324,wechat:"baiyangliu",email:"lc@baiyangliu.com"});' > me4.js
  
  - echo "$TEST_SPEED_JS" > test_speed.js
  - echo "$STATIC_JSON" > static.json
  
  - git init
  - git config --global user.name "baiyangliu" 
  - git config --global user.email "cun.liu@qq.com"
  - git add .
  - git commit -m "Updated by travis-ci at $(date)"
  - git push --force https://$DEPLOY_TOKEN@github.com/baiyangliu/baiyangliu.github.io.git master:master
  
  - echo -e "$SSH_KEY" > id_rsa
  - chmod 600 id_rsa
  - eval $(ssh-agent -s)
  - ssh-add id_rsa
  - rm -rf id_rsa
  - ssh -o "StrictHostKeyChecking no" git@git.oschina.net
  - ssh -o "StrictHostKeyChecking no" git@git.coding.net
  - git push --force git@git.coding.net:baiyangliu/baiyangliu.git master:master
  - git push --force git@git.oschina.net:baiyangliu/baiyangliu.git master:master