# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 小小白杨
subtitle: I'm a fatal bug!
description: 图样图森破(too young too simple,sometimes naive)
author: baiyangliu
language: zh-Hans
timezone: Asia/Shanghai
avatar: bug.png
since: 2012

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://baiyangliu.github.io
root: /
permalink: :title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: "    "

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page
  
robotstxt:
  useragent: "*"
  allow:
    - /
    - /archives/
    - /categories.html
    - /tags.html
    - /about.html
  disallow:
    - /page/
    - /js/
    - /images/
    - /imgs/
    - /css/
    - /lib/
  sitemap: /sitemap.xml

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repository: https://github.com/baiyangliu/baiyangliu.github.io
  branch: master
- type: git
  repository: https://git.coding.net/baiyangliu/baiyangliu.git
  branch: master
- type: git
  repository: https://git.oschina.net/baiyangliu/baiyangliu.git
  branch: master
- type: baidu_url_submitter

archive_generator:
  per_page: 0
  yearly: true
  monthly: true

tag_generator:
  per_page: 0


baidu_url_submit:
  count: 999
  host: baiyangliu.com
  token: zPRe1g0N1jYptQtA
  path: baidu_urls.txt
  

search: true

algolia:
  applicationID: '8IYI0XR3E5'
  apiKey: 'aa60ba3284d31eb23d09a7ab3d60bd80'
  indexName: 'baiyangliu'
  chunkSize: 5000
 
